-- Generated from JSON analysis
-- Generated on: 2025-08-28 03:15:39

DECLARE
  V_USERID TEXT;
  V_TRG_UPD_DATE_STR TEXT;

BEGIN
  IF  TG_OP = 'UPDATE'  THEN
    IF  COALESCE (OLD.PROD_FAM_NAME_STATUS_CD, 'X') <> COALESCE (NEW.PROD_FAM_NAME_STATUS_CD, 'X') OR OLD.PROD_FAM_NAME <> NEW.PROD_FAM_NAME OR COALESCE(OLD.ACT_SUBSTANCE_NAME, 'X') <> COALESCE(NEW.ACT_SUBSTANCE_NAME, 'X')  THEN
      CASE
        ELSE
          NULL;
      END CASE;
    END IF;
  END IF;
  RETURN NULL;
END;

-- End of generated SQL