DECLARE
   v_cntr PLS_INTEGER := 0;
   err_del EXCEPTION;
   err_upd EXCEPTION;
   err_upd2 EXCEPTION;
BEGIN
  IF  NVL(txo_util.get_userid,'GENERIC') = 'GENERIC'  THEN
    RAISE err_upd;
  END IF;
  IF  UPDATING AND :OLD.STATUS_CD IN ('D','A') AND :OLD.STATUS_CD = :NEW.STATUS_CD  THEN
    RAISE err_upd2;
  END IF;
  IF  UPDATING  THEN
    SELECT :NEW.REQUEST_ID ,:NEW.REQUEST_TYPE_CD ,:NEW.CODE ,:NEW.REQUEST_DATE ,:NEW.REQUESTOR_USERID ,:NEW.REQUESTOR ,:NEW.REVIEW_DATE ,:NEW.REVIEW_USERID ,:NEW.REVIEWER ,:NEW.APPROVAL_DATE ,:NEW.APPROVAL_USERID ,:NEW.APPROVER ,:NEW.CHANGED_OBJECTS ,:NEW.BLANK ,:NEW.LAST_UPDATE ,:NEW.STATUS_CD ,:NEW.REQUEST_COMMENT ,:NEW.REJECT_DATE ,:NEW.REJECT_USERID ,:NEW.REJECTER ,:NEW.IS_CPY_OR_REN ,:NEW.COMMENT_NEW INTO mdm_util_variables.request_admin_rec FROM DUAL;
    mdm_util_cfg_requests.mod_request;
  END IF;
EXCEPTION
  WHEN err_upd THEN
    RAISE_APPLICATION_ERROR;
  WHEN err_upd2 THEN
    RAISE_APPLICATION_ERROR;
  WHEN err_del THEN
    RAISE_APPLICATION_ERROR;
END;