-- PostgreSQL Trigger for trigger4_postgresql.json
-- Generated on: 2025-08-28 03:15:43

-- ON INSERT
DO $$
DECLARE
  V_ACTION TEXT;
  COL_NAMES TEXT[];
  COL_NEW_VALUES TEXT[];
  COL_OLD_VALUES TEXT[];
  V_TABLE_NAME TEXT := LOWER(TG_TABLE_NAME) || '_his';
  V_SCHEMA_NAME TEXT := LOWER(TG_TABLE_SCHEMA);
BEGIN
  IF TG_OP = '' THEN
  END IF;
  RETURN NULL;
END;
END $$;

-- ON UPDATE
DO $$
DECLARE
  V_ACTION TEXT;
  COL_NAMES TEXT[];
  COL_NEW_VALUES TEXT[];
  COL_OLD_VALUES TEXT[];
  V_TABLE_NAME TEXT := LOWER(TG_TABLE_NAME) || '_his';
  V_SCHEMA_NAME TEXT := LOWER(TG_TABLE_SCHEMA);
BEGIN
  IF TG_OP = '' THEN
  END IF;
  RETURN NULL;
END;
END $$;

-- ON DELETE
DO $$
DECLARE
  V_ACTION TEXT;
  COL_NAMES TEXT[];
  COL_NEW_VALUES TEXT[];
  COL_OLD_VALUES TEXT[];
  V_TABLE_NAME TEXT := LOWER(TG_TABLE_NAME) || '_his';
  V_SCHEMA_NAME TEXT := LOWER(TG_TABLE_SCHEMA);
BEGIN
  IF TG_OP = '' THEN
  END IF;
  RETURN NULL;
END;
END $$;
