-- PostgreSQL Trigger for trigger5_postgresql.json
-- Generated on: 2025-08-28 03:15:43

-- ON INSERT
DO $$
DECLARE
  V_USERID TEXT;
  V_TRG_UPD_DATE_STR TEXT;
BEGIN
  IF TG_OP = '' THEN
    IF COALESCE (OLD.PROD_FAM_NAME_STATUS_CD, 'X') <> COALESCE (NEW.PROD_FAM_NAME_STATUS_CD, 'X') OR OLD.PROD_FAM_NAME <> NEW.PROD_FAM_NAME OR COALESCE(OLD.ACT_SUBSTANCE_NAME, 'X') <> COALESCE(NEW.ACT_SUBSTANCE_NAME, 'X') THEN
      CASE
        WHEN  THEN
          UPDATE GMD.THEME_MOLECULES SET MOLECULE_DESC = NEW.PROD_FAM_NAME WHERE PRODUCT_FAMILY_CD = NEW.PRODUCT_FAMILY_CD;
        WHEN  THEN
          UPDATE GMD.THEME_MOLECULES SET MOLECULE_DESC = NEW.ACT_SUBSTANCE_NAME WHERE PRODUCT_FAMILY_CD = NEW.PRODUCT_FAMILY_CD;
        ELSE
          NULL;
      END CASE;
    END IF;
  END IF;
  RETURN NULL;
END;
END $$;

-- ON UPDATE
DO $$
DECLARE
  V_USERID TEXT;
  V_TRG_UPD_DATE_STR TEXT;
BEGIN
  IF TG_OP = '' THEN
    IF COALESCE (OLD.PROD_FAM_NAME_STATUS_CD, 'X') <> COALESCE (NEW.PROD_FAM_NAME_STATUS_CD, 'X') OR OLD.PROD_FAM_NAME <> NEW.PROD_FAM_NAME OR COALESCE(OLD.ACT_SUBSTANCE_NAME, 'X') <> COALESCE(NEW.ACT_SUBSTANCE_NAME, 'X') THEN
      CASE
        WHEN  THEN
          UPDATE GMD.THEME_MOLECULES SET MOLECULE_DESC = NEW.PROD_FAM_NAME WHERE PRODUCT_FAMILY_CD = NEW.PRODUCT_FAMILY_CD;
        WHEN  THEN
          UPDATE GMD.THEME_MOLECULES SET MOLECULE_DESC = NEW.ACT_SUBSTANCE_NAME WHERE PRODUCT_FAMILY_CD = NEW.PRODUCT_FAMILY_CD;
        ELSE
          NULL;
      END CASE;
    END IF;
  END IF;
  RETURN NULL;
END;
END $$;

-- ON DELETE
DO $$
DECLARE
  V_USERID TEXT;
  V_TRG_UPD_DATE_STR TEXT;
BEGIN
  IF TG_OP = '' THEN
    IF COALESCE (OLD.PROD_FAM_NAME_STATUS_CD, 'X') <> COALESCE (NEW.PROD_FAM_NAME_STATUS_CD, 'X') OR OLD.PROD_FAM_NAME <> NEW.PROD_FAM_NAME OR COALESCE(OLD.ACT_SUBSTANCE_NAME, 'X') <> COALESCE(NEW.ACT_SUBSTANCE_NAME, 'X') THEN
      CASE
        WHEN  THEN
          UPDATE GMD.THEME_MOLECULES SET MOLECULE_DESC = NEW.PROD_FAM_NAME WHERE PRODUCT_FAMILY_CD = NEW.PRODUCT_FAMILY_CD;
        WHEN  THEN
          UPDATE GMD.THEME_MOLECULES SET MOLECULE_DESC = NEW.ACT_SUBSTANCE_NAME WHERE PRODUCT_FAMILY_CD = NEW.PRODUCT_FAMILY_CD;
        ELSE
          NULL;
      END CASE;
    END IF;
  END IF;
  RETURN NULL;
END;
END $$;
