-- PostgreSQL Trigger for zzz_postgresql.json
-- Generated on: 2025-09-03 07:13:16

-- ON INSERT
DO $$ DECLARE v_holiday_descs txo_varchar_coll; v_country_codes txo_varchar_coll; v_chk_is_multivalue numeric; v_chk_distinct numeric; BEGIN WITH H c AS AS ( SELECT TRIM(SUBSTRING(:new.HOLIDAY_NAME, '[^,]+', 1, nan)) col FROM dual CONNECT BY SUBSTRING(:new.HOLIDAY_NAME, '[^,]+', 1, nan) IS NOT NULL) SELECT SUBSTRING(c.col, '[^[]+', 1) holiday_desc, SUBSTRING(c.col, '[^[]+[^]]', 1, 2) country_cd BULK COLLECT INTO v_holiday_descs, v_country_codes FROM c; SELECT COUNT(country_cd), COUNT(column_value) - COUNT(distinct column_value ) -- Unknown statement type: unknown -- Unknown statement type: unknown -- Unknown statement type: unknown -- Unknown statement type: unknown -- Unknown statement type: unknown RAISE EXCEPTION err_upd2; -- Unknown statement type: unknown RAISE EXCEPTION err_upd3; -- Unknown statement type: unknown END; $$ LANGUAGE plpgsql;

-- ON UPDATE
DO $$ DECLARE v_holiday_descs txo_varchar_coll; v_country_codes txo_varchar_coll; v_chk_is_multivalue numeric; v_chk_distinct numeric; BEGIN WITH H c AS AS ( SELECT TRIM(SUBSTRING(:new.HOLIDAY_NAME, '[^,]+', 1, nan)) col FROM dual CONNECT BY SUBSTRING(:new.HOLIDAY_NAME, '[^,]+', 1, nan) IS NOT NULL) SELECT SUBSTRING(c.col, '[^[]+', 1) holiday_desc, SUBSTRING(c.col, '[^[]+[^]]', 1, 2) country_cd BULK COLLECT INTO v_holiday_descs, v_country_codes FROM c; SELECT COUNT(country_cd), COUNT(column_value) - COUNT(distinct column_value ) -- Unknown statement type: unknown -- Unknown statement type: unknown -- Unknown statement type: unknown -- Unknown statement type: unknown -- Unknown statement type: unknown RAISE EXCEPTION err_upd2; -- Unknown statement type: unknown RAISE EXCEPTION err_upd3; -- Unknown statement type: unknown END; $$ LANGUAGE plpgsql;

-- ON DELETE
DO $$ DECLARE v_holiday_descs txo_varchar_coll; v_country_codes txo_varchar_coll; v_chk_is_multivalue numeric; v_chk_distinct numeric; BEGIN WITH H c AS AS ( SELECT TRIM(SUBSTRING(:new.HOLIDAY_NAME, '[^,]+', 1, nan)) col FROM dual CONNECT BY SUBSTRING(:new.HOLIDAY_NAME, '[^,]+', 1, nan) IS NOT NULL) SELECT SUBSTRING(c.col, '[^[]+', 1) holiday_desc, SUBSTRING(c.col, '[^[]+[^]]', 1, 2) country_cd BULK COLLECT INTO v_holiday_descs, v_country_codes FROM c; SELECT COUNT(country_cd), COUNT(column_value) - COUNT(distinct column_value ) -- Unknown statement type: unknown -- Unknown statement type: unknown -- Unknown statement type: unknown -- Unknown statement type: unknown -- Unknown statement type: unknown RAISE EXCEPTION err_upd2; -- Unknown statement type: unknown RAISE EXCEPTION err_upd3; -- Unknown statement type: unknown END; $$ LANGUAGE plpgsql;
